config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :property_users
  resources :properties
  resources :users
  post "/login", to: "users#login"
  get "/auto_login", to: "users#auto_login"
  post "/signup", to: "users#create"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :property
  validates :name, presence: true
  validates :url, presence: true
end

app/models/property.rb
class Property < ApplicationRecord
    has_many :photos, dependent: :destroy
    has_many :property_users
    has_many :users, through: :property_users
    validates :name, presence: true
    validates :operation_type, presence: true
    validates :address, presence: true
    validates :phone, presence: true
    validates :address, length: { maximum: 140, message: 'Cannot be more than 140 characters' }
end
  

app/models/property_user.rb
class PropertyUser < ApplicationRecord
  belongs_to :user
  belongs_to :property
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    enum role: { admin: 'landlord', user: 'homeseeker' }
    has_many :property_users
    has_many :properties, through: :property_users
    validates :name, presence: true
    validates :username, presence: true
    validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/ }
    validates :password, length: { minimum: 6 }, allow_nil: true
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
    before_action :authorized
  
    def encode_token(payload)
      JWT.encode(payload, 'yourSecret')
    end
  
    def auth_header
      # { Authorization: 'Bearer <token>' }
      request.headers['Authorization']
    end
  
    def decoded_token
      if auth_header
        token = auth_header.split(' ')[1]
        # header: { 'Authorization': 'Bearer <token>' }
        begin
          JWT.decode(token, 'yourSecret', true, algorithm: 'HS256')
        rescue JWT::DecodeError
          nil
        end
      end
    end
  
    def logged_in_user
      if decoded_token
        user_id = decoded_token[0]['user_id']
        @user = User.find_by(id: user_id)
      end
    end
  
    def logged_in?
      !!logged_in_user
    end
  
    def authorized
      render json: { message: 'Please log in' }, status: :unauthorized unless logged_in?
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[update show destroy]
  before_action :authorized, only: %i[create update destroy]
  def index
    @photos = Photo.all
    render json: @photos
  end

  # POST /properties
  def create
    photo = Cloudinary::Uploader.upload(params[:image])
    photo_name = params[:name]
    property_id = params[:property_id]
    @photo_new = Photo.create(name: photo_name, url: photo['url'], property_id: property_id)
    if @photo_new.valid?
      render json: @photo_new, status: :created
    else
      render json: @photo_new.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /properties/id
  def update
    if @photo.update(photo_params)
      render json: @photo
    else
      render json: @photo.errors, status: :unprocessable_entity
    end
  end

  # GET /properties/id
  def show
    render json: @photo
  end

  # DELETE /properties/id
  def destroy
    @photo.destroy
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:name, :url, :property_id)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[show update destroy]
  before_action :authorized, only: %i[create update destroy]
  # GET /properties
  def index
    @properties = Property.all
    render json: @properties
  end

  # GET /properties/:id
  def show
    render json: { property: @property, photos: @property.photos }
  end

  # POST /properties
  def create
    @property_new = Property.create(property_params)
    if @property_new.valid?
      render json: @property_new, status: :created
    else
      render json: @property_new.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /properties/id
  def update
    if @property.update(property_params)
      render json: @property
    else
      render json: @property.errors, status: :unprocessable_entity
    end
  end

  # DELETE /properties/id
  def destroy
    @property.destroy
  end

  private
  
  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:name, :operation_type, :address, :phone, :price, :property_type, :bedrooms,
                                     :bathrooms, :area, :pets, :description, :lng, :lat)
  end
end

app/controllers/property_users_controller.rb
class PropertyUsersController < ApplicationController
  before_action :set_property_user, only: %i[update destroy]
  before_action :authorized, only: %i[create update destroy]
  def index
    @property_users = PropertyUser.all
    render json: @property_users
  end

  def create
    @property_user_new = PropertyUser.create(property_user_params)
    if @property_user_new.valid?
      render json: @property_user_new, status: :created
    else
      render json: @property_users_new.errors, status: :unprocessable_entity
    end
  end

  def update
    if @property_user.update(property_user_params)
      render json: @property_user
    else
      render json: @property_user.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @property_user.destroy
  end

  private

  def set_property_user
    @property_user = PropertyUser.find(params[:id])
  end

  def property_user_params
    params.require(:property_user).permit(:favorite, :closed, :contacted, :user_id, :property_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized, only: %i[auto_login show]

  # REGISTER
  def create
    @user = User.create(user_params)
    if @user.valid?
      token = encode_token({user_id: @user.id})
      render json: {user: @user, token: token}
    else
      render json: {error: "Invalid username or password"}
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render json: { user: @user, properties: @user.properties }
  end
  # LOGGING IN
  def login
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      token = encode_token({user_id: @user.id})
      render json: {user: @user, token: token}
    else
      render json: {error: "Invalid email or password"}
    end
  end


  def auto_login
    render json: @user
  end

  private

  def user_params
    params.permit(:email, :password, :username, :role, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/property_users_helper.rb
module PropertyUsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiGetThatHome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo) do |form| %>
  <% if photo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :property_id, style: "display: block" %>
    <%= form.text_field :property_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div id="<%= dom_id photo %>">
  <p>
    <strong>Name:</strong>
    <%= photo.name %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= photo.url %>
  </p>

  <p>
    <strong>Property:</strong>
    <%= photo.property_id %>
  </p>

</div>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Show this photo", @photo %> |
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Photos</h1>

<div id="photos">
  <% @photos.each do |photo| %>
    <%= render photo %>
    <p>
      <%= link_to "Show this photo", photo %>
    </p>
  <% end %>
</div>

<%= link_to "New photo", new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @photo %>

<div>
  <%= link_to "Edit this photo", edit_photo_path(@photo) %> |
  <%= link_to "Back to photos", photos_path %>

  <%= button_to "Destroy this photo", @photo, method: :delete %>
</div>

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :operation_type, style: "display: block" %>
    <%= form.text_field :operation_type %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :property_type, style: "display: block" %>
    <%= form.text_field :property_type %>
  </div>

  <div>
    <%= form.label :bedrooms, style: "display: block" %>
    <%= form.number_field :bedrooms %>
  </div>

  <div>
    <%= form.label :bathrooms, style: "display: block" %>
    <%= form.number_field :bathrooms %>
  </div>

  <div>
    <%= form.label :area, style: "display: block" %>
    <%= form.text_field :area %>
  </div>

  <div>
    <%= form.label :pets, style: "display: block" %>
    <%= form.check_box :pets %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>">
  <p>
    <strong>Name:</strong>
    <%= property.name %>
  </p>

  <p>
    <strong>Operation type:</strong>
    <%= property.operation_type %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= property.address %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= property.phone %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= property.price %>
  </p>

  <p>
    <strong>Property type:</strong>
    <%= property.property_type %>
  </p>

  <p>
    <strong>Bedrooms:</strong>
    <%= property.bedrooms %>
  </p>

  <p>
    <strong>Bathrooms:</strong>
    <%= property.bathrooms %>
  </p>

  <p>
    <strong>Area:</strong>
    <%= property.area %>
  </p>

  <p>
    <strong>Pets:</strong>
    <%= property.pets %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= property.description %>
  </p>

</div>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Show this property", @property %> |
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Properties</h1>

<div id="properties">
  <% @properties.each do |property| %>
    <%= render property %>
    <p>
      <%= link_to "Show this property", property %>
    </p>
  <% end %>
</div>

<%= link_to "New property", new_property_path %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @property %>

<div>
  <%= link_to "Edit this property", edit_property_path(@property) %> |
  <%= link_to "Back to properties", properties_path %>

  <%= button_to "Destroy this property", @property, method: :delete %>
</div>

app/views/property_users/_form.html.erb
<%= form_with(model: property_user) do |form| %>
  <% if property_user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(property_user.errors.count, "error") %> prohibited this property_user from being saved:</h2>

      <ul>
        <% property_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :favorite, style: "display: block" %>
    <%= form.check_box :favorite %>
  </div>

  <div>
    <%= form.label :closed, style: "display: block" %>
    <%= form.check_box :closed %>
  </div>

  <div>
    <%= form.label :contacted, style: "display: block" %>
    <%= form.check_box :contacted %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :property_id, style: "display: block" %>
    <%= form.text_field :property_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/property_users/_property_user.html.erb
<div id="<%= dom_id property_user %>">
  <p>
    <strong>Favorite:</strong>
    <%= property_user.favorite %>
  </p>

  <p>
    <strong>Closed:</strong>
    <%= property_user.closed %>
  </p>

  <p>
    <strong>Contacted:</strong>
    <%= property_user.contacted %>
  </p>

  <p>
    <strong>User:</strong>
    <%= property_user.user_id %>
  </p>

  <p>
    <strong>Property:</strong>
    <%= property_user.property_id %>
  </p>

</div>

app/views/property_users/edit.html.erb
<h1>Editing property user</h1>

<%= render "form", property_user: @property_user %>

<br>

<div>
  <%= link_to "Show this property user", @property_user %> |
  <%= link_to "Back to property users", property_users_path %>
</div>

app/views/property_users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Property users</h1>

<div id="property_users">
  <% @property_users.each do |property_user| %>
    <%= render property_user %>
    <p>
      <%= link_to "Show this property user", property_user %>
    </p>
  <% end %>
</div>

<%= link_to "New property user", new_property_user_path %>

app/views/property_users/new.html.erb
<h1>New property user</h1>

<%= render "form", property_user: @property_user %>

<br>

<div>
  <%= link_to "Back to property users", property_users_path %>
</div>

app/views/property_users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @property_user %>

<div>
  <%= link_to "Edit this property user", edit_property_user_path(@property_user) %> |
  <%= link_to "Back to property users", property_users_path %>

  <%= button_to "Destroy this property user", @property_user, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %> <% if user.errors.any? %>
<div style="color: red">
	<h2>
		<%= pluralize(user.errors.count, "error") %> prohibited this user from being
		saved:
	</h2>

	<ul>
		<% user.errors.each do |error| %>
		<li><%= error.full_message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div>
	<%= form.label :username, style: "display: block" %> <%= form.text_field
	:username %>
</div>

<div>
	<%= form.label :email, style: "display: block" %> <%= form.text_field :email
	%>
</div>

<div>
	<%= form.label :password_diget, style: "display: block" %> <%=
	form.text_field :password_digest %>
</div>

<div>
	<%= form.label :role, style: "display: block" %> <%= form.text_field :role %>
</div>

<div><%= form.submit %></div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= user.role %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>